# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('submitted_date', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_class', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureClassArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'wqual_feature_class_args',
            },
        ),
        migrations.CreateModel(
            name='FeatureFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=45)),
                ('factory_class', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'wqual_feature_factory',
            },
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wqual_feature_set',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('year', models.IntegerField()),
                ('authors', models.ManyToManyField(to='wqual.Author')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Feature')),
                ('feature_class_args', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.FeatureClassArgs')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.FeatureSet')),
            ],
            options={
                'db_table': 'wqual_used_feature',
            },
        ),
        migrations.AddField(
            model_name='featureset',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Language'),
        ),
        migrations.AddField(
            model_name='featureset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='feature_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.FeatureSet'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Format'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wqual.Status'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
