# Generated by Django 2.0.1 on 2018-01-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretimeperdocument',
            name='val_cost_time',
        ),
    ]
