# Generated by Django 2.0.1 on 2018-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqual.Dataset'),
        ),
        migrations.AlterField(
            model_name='documentresult',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wqual.Document'),
        ),
        migrations.AlterField(
            model_name='documenttext',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wqual.Document'),
        ),
    ]
