# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureset',
            name='group',
            field=models.CharField(default='g1', max_length=50),
            preserve_default=False,
        ),
    ]
