# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='num_proc_extractor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usedfeature',
            name='feature_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqual.FeatureSet'),
        ),
        migrations.AlterField(
            model_name='usedfeatureargval',
            name='used_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqual.UsedFeature'),
        ),
    ]
