# Generated by Django 2.0.1 on 2018-01-30 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0002_remove_featuretimeperdocument_val_cost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretimeperdocument',
            name='val_cost_time',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
