# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0002_feature_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_datasets')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wqual.Dataset')),
            ],
        ),
    ]
