# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0002_feature_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='bol_ready_to_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featureset',
            name='bol_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
