# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0002_featureset_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureset',
            name='group',
        ),
    ]
