# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import wqual.models.uploaded_datasets


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0003_submitteddataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureset',
            name='nam_feature_set',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submitteddataset',
            name='file',
            field=models.FileField(upload_to=wqual.models.uploaded_datasets.content_file_name),
        ),
    ]
