# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-08 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import wqual.models.uploaded_datasets


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0003_submitteddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='num_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitteddataset',
            name='file',
            field=models.FileField(upload_to=wqual.models.uploaded_datasets.content_file_name),
        ),
    ]
