# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wqual', '0003_remove_featureset_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featureset',
            unique_together=set([('nam_feature_set', 'user')]),
        ),
        migrations.AddIndex(
            model_name='featureset',
            index=models.Index(fields=['nam_feature_set', 'user'], name='wqual_featu_nam_fea_46fef1_idx'),
        ),
    ]
