# Generated by Django 2.0.1 on 2018-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0003_featuretimeperdocument_val_cost_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretimeperdocument',
            name='val_cost_time',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
