# Generated by Django 2.0.1 on 2018-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0004_auto_20180130_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretimeperdocument',
            name='val_cost_time',
        ),
    ]
