# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0004_auto_20171023_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedfeature',
            name='ord_feature',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedfeature',
            name='text_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wqual.Format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedfeatureargval',
            name='type_argument',
            field=models.CharField(choices=[('int', 'int'), ('string', 'string'), ('json', 'json')], default='string', max_length=10),
        ),
    ]
