# Generated by Django 2.0.1 on 2018-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0005_remove_featuretimeperdocument_val_cost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dsc_result_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentresult',
            name='dsc_result',
            field=models.TextField(),
        ),
    ]
