# Generated by Django 2.1.1 on 2018-10-02 20:24

from django.db import migrations, models
SOURCES = [{"id":1,"nam_source":"Textual"},
            {"id":2,"nam_source":"Graph"},
            {"id":3,"nam_source":"Revision"}]
def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Source = apps.get_model("wqual", "Source")
    db_alias = schema_editor.connection.alias
    arrToInsert = [Source(**source) for source in SOURCES]#Instancia cada Source dado os atributos que existem no dicionario

    Source.objects.using(db_alias).bulk_create(arrToInsert)

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Source = apps.get_model("wqual", "Source")
    db_alias = schema_editor.connection.alias
    ids = [source["id"] for source in SOURCES]
    Source.objects.using(db_alias).filter(id__in=ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0005_auto_20181002_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nam_source', models.CharField(max_length=45)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
