# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0005_auto_20171218_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedfeature',
            name='is_configurable',
            field=models.BooleanField(default=False),
        ),
    ]
