# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0006_usedfeature_is_configurable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedfeature',
            name='is_configurable',
        ),
        migrations.AddField(
            model_name='usedfeatureargval',
            name='is_configurable',
            field=models.BooleanField(default=False),
        ),
    ]
