# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0007_auto_20171218_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedfeatureargval',
            name='val_argument',
            field=models.CharField(max_length=5000),
        ),
    ]
