# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0007_auto_20171218_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dsc_result_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='end_dat_processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='start_dat_processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
