# Generated by Django 2.0.1 on 2018-01-19 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0007_auto_20171218_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentresult',
            name='dsc_result',
        ),
        migrations.AddField(
            model_name='dataset',
            name='end_dat_processing',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='start_dat_processing',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
