# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0008_auto_20180215_1804'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='usedfeature',
            name='feature_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqual.FeatureSet'),
        ),
        migrations.AlterField(
            model_name='usedfeatureargval',
            name='type_argument',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('string', 'string'), ('boolean', 'boolean'), ('json', 'json'), ('json_set', 'json_set')], default='string', max_length=10),
        ),
        migrations.AlterField(
            model_name='usedfeatureargval',
            name='used_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqual.UsedFeature'),
        ),
    ]
