# Generated by Django 2.0 on 2018-12-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0008_featureset_int_source_id'),
        ('wqual', '0005_auto_20181109_1015'),
    ]

    operations = [
    ]
