# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wqual', '0008_remove_documentresult_dsc_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedfeatureargval',
            name='dsc_argument',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usedfeatureargval',
            name='json_choices',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
